"""
Django settings for littleTalk project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Setting up env to inject syst variables
load_dotenv("/etc/littleTalk/littleTalk.env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: SECRET KEY MUST NOT BE PLAINLY EXPOSED, INJECT FROM A SECURE ENVIRONMENT VARIABLE
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("Missing DJANGO_SECRET_KEY environment variable")

# SECURITY WARNING: DEBUG MUST REMAIN TRUE IN PRODUCTION
DEBUG = False

ALLOWED_HOSTS = [
    "chatterdillo.com",
    "www.chatterdillo.com",
    "little-talk.org",
    "www.little-talk.org",
    "chatterdillo.org",
    "www.chatterdillo.org",
    "116.203.197.92",
]


# Application definition

INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'littleTalkApp',
    'rest_framework',
    'corsheaders',
    'honeypot',
    'django_vite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'littleTalkApp.middleware.NoCacheHtmlMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'littleTalkApp.middleware.AccessControlMiddleware',
    'littleTalkApp.middleware.RoleSchoolBlockMiddleware',
    'littleTalkApp.middleware.SchoolSelectionMiddleware',
]

ROOT_URLCONF = 'littleTalk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'littleTalk.context_processors.layout_context',
                'littleTalk.context_processors.canonical_url',
                'littleTalk.context_processors.marketing_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'littleTalk.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Custom user model
AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'

CORS_ALLOWED_ORIGINS = [
    "https://little-talk.org",
    "https://www.little-talk.org",
]

CORS_ALLOW_CREDENTIALS = True

# Email Contact Us Section Setup

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.eu'  # or smtp.zoho.com depending on your Zoho region
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'noreply@chatterdillo.com'

EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
if not EMAIL_HOST_PASSWORD:
    raise ValueError("Missing EMAIL_HOST_PASSWORD environment variable")

DEFAULT_FROM_EMAIL = 'noreply@chatterdillo.com'

# Encryption
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY')

if not FIELD_ENCRYPTION_KEY:
    raise ValueError("Missing FIELD_ENCRYPTION_KEY environment variable")

# stripe payments
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
if not STRIPE_SECRET_KEY:
    raise ValueError("Missing STRIPE_SECRET_KEY environment variable")

STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
if not STRIPE_PUBLISHABLE_KEY:
    raise ValueError("Missing STRIPE_PUBLISHABLE_KEY environment variable")

STRIPE_PARENT_PRICE_ID = "price_1S08FVLKb9r84s77cNhlzChi"

STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
if not STRIPE_WEBHOOK_SECRET:
    raise ValueError("Missing STRIPE_WEBHOOK_SECRET environment variable")

# Skolon integration
SKOLON_CLIENT_ID = os.getenv('SKOLON_CLIENT_ID')
if not SKOLON_CLIENT_ID:
    raise ValueError("Missing SKOLON_CLIENT_ID environment variable")

SKOLON_CLIENT_SECRET = os.getenv('SKOLON_CLIENT_SECRET')
if not SKOLON_CLIENT_SECRET:
    raise ValueError("Missing SKOLON_CLIENT_SECRET environment variable")

SKOLON_ENV = os.getenv('SKOLON_ENV', 'production')

SKOLON_IDP_BASE_URL = (
    'https://idp.skolon.com'
    if SKOLON_ENV == 'production'
    else 'https://idp-test.skolon.com'
)

SKOLON_TOKEN_URL = (
    'https://idp.skolon.com/oauth/access_token'
    if SKOLON_ENV == 'production'
    else 'https://idp-test.skolon.com/oauth/access_token'
)
SKOLON_API_BASE_URL = (
    'https://api.skolon.com'
    if SKOLON_ENV == 'production'
    else 'https://api-test.skolon.com'
)
SKOLON_SSO_CALLBACK_URL = os.getenv('SKOLON_SSO_CALLBACK_URL', 'https://chatterdillo.com/sso/callback')

# Calendly Settings
CALENDLY_URL = 'https://calendly.com/chatterdillo-support/30min'

# Honeypot settings
HONEYPOT_FIELD_NAME = 'contact_info'

# DRF settings
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# Security settings
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Exempt webhooks from SSL redirect
SECURE_REDIRECT_EXEMPT = [r'^webhooks/stripe/$', r'^webhooks/skolon/']

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'littleTalkApp.views': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# SECURITY WARNING: DEV MODE MUST REMAIN FALSE IN PRODUCTION
DJANGO_VITE = {
    "default": {
        "dev_mode": False,
        "manifest_path": os.path.join(BASE_DIR, "static/js/exercises/manifest.json"),
        "static_url_prefix": "js/exercises",
    }
}
