"""
Django settings for littleTalk project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-b3z1ks+&tjb740$cqbuxv$&49x06!)v#*d@ae+!m@5#rjtyesc"

# SECURITY WARNING: don't run with debug turned on in production!

# -=-=-=-=-=-= DEV -=-=-=-=-=-=

DEBUG = True

ALLOWED_HOSTS = ["LITTLE-TALK.ORG", "116.203.197.92", "127.0.0.1", "localhost"]

# -=-=-=-=-=-= PROD -=-=-=-=-=-=

# DEBUG = False

# ALLOWED_HOSTS = ['LITTLE-TALK.ORG', '116.203.197.92']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "littleTalkApp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "littleTalkApp.middleware.AccessControlMiddleware",
    "littleTalkApp.middleware.RoleSchoolBlockMiddleware",
]

ROOT_URLCONF = "littleTalk.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "littleTalk.context_processors.layout_context",  # Add this line
            ],
        },
    },
]

WSGI_APPLICATION = "littleTalk.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "main",
        "USER": "admin",
        "PASSWORD": "admin",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -=-=-=-=-=-= DEV -=-=-=-=-=-=
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# -=-=-=-=-=-= PROD -=-=-=-=-=-=
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

LOGIN_REDIRECT_URL = "/profile/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_URL = "/login/"

# encryption

load_dotenv()

# EMAIL

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.zoho.eu"  # or smtp.zoho.com depending on your Zoho region
EMAIL_HOST = "email"  # or smtp.zoho.com depending on your Zoho region
# EMAIL_PORT = 587
EMAIL_PORT = 1025
# EMAIL_USE_TLS = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = "noreply@chatterdillo.com"

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# Get the key from env
FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY")

if not FIELD_ENCRYPTION_KEY:
    raise ValueError("Missing FIELD_ENCRYPTION_KEY environment variable")

# stripe payments
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
if not STRIPE_SECRET_KEY:
    raise ValueError("Missing STRIPE_SECRET_KEY environment variable")

STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
if not STRIPE_PUBLISHABLE_KEY:
    raise ValueError("Missing STRIPE_PUBLISHABLE_KEY environment variable")

STRIPE_PARENT_PRICE_ID = "price_1RtSAiL44mGM9HHxUScSlpdA"

STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
if not STRIPE_WEBHOOK_SECRET:
    raise ValueError("Missing STRIPE_WEBHOOK_SECRET environment variable")
