"""Screener V2 question definitions and recommendation metadata."""

from littleTalkApp.exercise_ids import VALID_EXERCISE_IDS

QUESTIONS_V2 = [
    {
        "order": 1,
        "topic": "Attention and Listening",
        "skill": "Attention and listening",
        "text": "Can the child attend to an activity for 5 minutes?",
        "stage": None,
        "blank_level": None,
        "exercise_id": None,
        "is_readiness": True,
    },
    {
        "order": 2,
        "topic": "Attention and Listening",
        "skill": "Attention and listening",
        "text": "Can the child point to/choose the correct object when named?",
        "stage": None,
        "blank_level": None,
        "exercise_id": None,
        "is_readiness": True,
    },
    {
        "order": 3,
        "topic": "Blank Level 1",
        "skill": "Naming common objects",
        "text": "Can the child name everyday objects (e.g. chair, hat, bag, toy)?",
        "stage": 1,
        "blank_level": 1,
        "exercise_id": "whats-in-the-bag",
        "is_readiness": False,
    },
    {
        "order": 4,
        "topic": "Blank Level 1",
        "skill": "Vocabulary development",
        "text": "Does the child regularly use new words they have recently learned?",
        "stage": 1,
        "blank_level": 1,
        "exercise_id": "whats-in-the-bag",
        "is_readiness": False,
    },
    {
        "order": 5,
        "topic": "Blank Level 1",
        "skill": "Understanding prepositions",
        "text": "Can the child understand simple position words (e.g. in, on, under)?",
        "stage": 1,
        "blank_level": 1,
        "exercise_id": "spot-on",
        "is_readiness": False,
    },
    {
        "order": 6,
        "topic": "Blank Level 1",
        "skill": "Following pronoun instructions",
        "text": "Can the child follow pronoun-based instructions (e.g. 'give the ball to her')?",
        "stage": 1,
        "blank_level": 1,
        "exercise_id": "whos-who",
        "is_readiness": False,
    },
    {
        "order": 7,
        "topic": "Blank Level 1",
        "skill": "Using action words",
        "text": "Can the child understand action words (e.g. eating, running, jumping)?",
        "stage": 1,
        "blank_level": 1,
        "exercise_id": "colourful-semantics-early",
        "is_readiness": False,
    },
    {
        "order": 8,
        "topic": "Blank Level 2",
        "skill": "Answering 'who/what/where' questions",
        "text": "Can the child answer 'who', 'what', or 'where' questions?",
        "stage": 2,
        "blank_level": 2,
        "exercise_id": "colourful-semantics",
        "is_readiness": False,
    },
    {
        "order": 9,
        "topic": "Blank Level 2",
        "skill": "Understanding concepts",
        "text": "Can the child understand descriptive concepts like 'big or small'?",
        "stage": 2,
        "blank_level": 2,
        "exercise_id": "concept-quest",
        "is_readiness": False,
    },
    {
        "order": 10,
        "topic": "Blank Level 2",
        "skill": "Grouping things together",
        "text": "Can the child group items that belong together (e.g. animals, foods, clothes)?",
        "stage": 2,
        "blank_level": 2,
        "exercise_id": "categorisation",
        "is_readiness": False,
    },
    {
        "order": 11,
        "topic": "Blank Level 2",
        "skill": "Understanding time concepts",
        "text": "Can the child talk about when something happens (e.g. 'in the morning', 'at night')?",
        "stage": 2,
        "blank_level": 2,
        "exercise_id": "story-train",
        "is_readiness": False,
    },
    {
        "order": 12,
        "topic": "Blank Level 2",
        "skill": "Following multi-step instructions",
        "text": "Can the child follow multi-step instructions (e.g. 'Put your shoes on and wait by the door')?",
        "stage": 2,
        "blank_level": 2,
        "exercise_id": "think-and-find",
        "is_readiness": False,
    },
    {
        "order": 13,
        "topic": "Blank Level 3",
        "skill": "Describing and sequencing events",
        "text": "Can the child describe events in the right order (what happened first, next, and last)?",
        "stage": 2,
        "blank_level": 3,
        "exercise_id": "story-train",
        "is_readiness": False,
    },
    {
        "order": 14,
        "topic": "Blank Level 3",
        "skill": "Retelling events/stories",
        "text": "Can the child retell something that has happened or a simple story?",
        "stage": 3,
        "blank_level": 3,
        "exercise_id": "story-train-plus",
        "is_readiness": False,
    },
    {
        "order": 15,
        "topic": "Blank Level 3",
        "skill": "Understanding emotions/mental states",
        "text": "Can the child work out how someone is feeling from a situation or picture?",
        "stage": 3,
        "blank_level": 3,
        "exercise_id": "in-the-know",
        "is_readiness": False,
    },
    {
        "order": 16,
        "topic": "Blank Level 4",
        "skill": "Answering 'why/how' questions",
        "text": "Can the child answer 'why' or 'how' questions?",
        "stage": 3,
        "blank_level": 4,
        "exercise_id": "colourful-semantics-plus",
        "is_readiness": False,
    },
    {
        "order": 17,
        "topic": "Blank Level 4",
        "skill": "Predicting outcomes",
        "text": "Can the child say what might happen next in a story or situation?",
        "stage": 3,
        "blank_level": 4,
        "exercise_id": "what-happens-next",
        "is_readiness": False,
    },
    {
        "order": 18,
        "topic": "Blank Level 4",
        "skill": "Giving sequential instructions",
        "text": "Can the child give clear step-by-step instructions (e.g. 'How do you brush your teeth?')?",
        "stage": 3,
        "blank_level": 4,
        "exercise_id": "task-master",
        "is_readiness": False,
    },
    {
        "order": 19,
        "topic": "Blank Level 4",
        "skill": "Justifying with evidence",
        "text": "Can the child explain how they know something (e.g. 'How do you know the girl is upset?')?",
        "stage": 3,
        "blank_level": 4,
        "exercise_id": "in-the-know",
        "is_readiness": False,
    },
]

STAGE_3_PADDING_ORDER = [
    "colourful-semantics-plus",
    "story-train-plus",
    "what-happens-next",
    "task-master",
    "in-the-know",
]


def get_question_by_order(order):
    return next((q for q in QUESTIONS_V2 if q["order"] == order), None)


def validate_v2_exercise_ids():
    invalid = []
    for question in QUESTIONS_V2:
        exercise_id = question.get("exercise_id")
        if exercise_id and exercise_id not in VALID_EXERCISE_IDS:
            invalid.append(exercise_id)
    return invalid
