GAME_DESCRIPTIONS = {
        'colourful_semantics': {
            'exercise_complexity': 0,
            'title': 'Colourful Semantics',
            'target': 'Sentence Building',
            'description': "Colourful Semantics helps children understand what words mean, how words fit together, and how to create simple, meaningful sentences. It uses colors to group words, making it easier for your child to remember words, learn new vocabulary, and express themselves clearly. Research shows that visual grouping of words into colors helps children better understand language and remember words more effectively.",
            'youtube_video_id': 'JXC1VueOriY',
            'bullet1': """Name objects, people, actions - "What is this?""",
            'bullet2': """Repeat a sentence - "Let's say, the dog is sitting.”""",
            'bullet3': """Describe a scene - “What's happening in this picture?”""",
            'learninglevel1': "If the child you are practising with is still learning their first few words (around 5 words or less), try the first two easier levels. These will focus on learning nouns (names of things and people) and verbs (action words). Many children find verbs tricky at first, so these levels will help.",
            'learninglevel2': 'If they already know some words and you want to help them start building sentences, pick higher difficulty levels to encourage them to put words together into simple sentences.',
            'static_name': 'colourful_semantics',
        },
        'colourful_semantics_early_sentence_building': {
            'exercise_complexity': 0,
            'title': 'Colourful Semantics Early',
            'target': 'Sentence Building',
            'description': "Colourful Semantics helps children understand what words mean, how words fit together, and how to create simple, meaningful sentences. It uses colors to group words, making it easier for your child to remember words, learn new vocabulary, and express themselves clearly. Research shows that visual grouping of words into colors helps children better understand language and remember words more effectively.",
            'youtube_video_id': 'JXC1VueOriY',
            'bullet1': 'Name objects, people, actions - "what is this?"',
            'bullet2': 'Repeat a sentence - "The dog is sitting"',
            'bullet3': 'Describe a scene - "what\'s happening in this picture?"',
            'learninglevel1': "If the child you are practising with is still learning their first few words (around 5 words or less), try the first two easier levels. These will focus on learning nouns (names of things and people) and verbs (action words). Many children find verbs tricky at first, so these levels will help.",
            'learninglevel2': 'If they already know some words and you want to help them start building sentences, pick higher difficulty levels to encourage them to put words together into simple sentences.',
            'static_name': 'colourful_semantics',
        },
        'colourful_semantics_advanced_sentence_building': {
            'exercise_complexity': 0,
            'title': 'Colourful Semantics Plus',
            'target': 'Sentence Building',
            'description': "Colourful Semantics helps children understand what words mean, how words fit together, and how to create simple, meaningful sentences. It uses colors to group words, making it easier for your child to remember words, learn new vocabulary, and express themselves clearly. Research shows that visual grouping of words into colors helps children better understand language and remember words more effectively.",
            'youtube_video_id': 'JXC1VueOriY',
            'bullet1': "Name objects, people, actions - \"What is this?\"",
            'bullet2': "Repeat a sentence - \"Let's say, the dog is sitting.\"",
            'bullet3': "Describe a scene - \"What's happening in this picture?\"",
            'learninglevel1': "If the child you are practising with is still learning their first few words (around 5 words or less), try the first two easier levels. These will focus on learning nouns (names of things and people) and verbs (action words). Many children find verbs tricky at first, so these levels will help.",
            'learninglevel2': 'If they already know some words and you want to help them start building sentences, pick higher difficulty levels to encourage them to put words together into simple sentences.',
            'static_name': 'colourful_semantics',
        },
        'think_and_find': {
            'exercise_complexity': 1,
            'title': 'Think and Find',
            'target': 'General Concepts',
            'quote': '"Linking items to concepts helps children structure their thoughts and enhances memory and retrieval capabilities" (Anderson & Freebody, 1981).',
            'description': "Think and Find is a matching activity that helps children learn new words and practise important thinking skills. It encourages children to develop conceptual thinking by matching pictures based on characteristics, improving their ability to notice details and make connections. This supports language growth, memory, and decision-making. It also serves as a natural path to categoristaion.",
            'youtube_video_id': 'wUCTDhj-1kw',
            'bullet1': """Point to / find an object - "Can you point to the lorry?""",
            'bullet2': """Match pictures and objects - “Can you find a car like this?”""",
            'bullet3': """Identify & describe characteristics: “What shape is this?”""",
            'learninglevel1': "We recommend starting with the easiest level first. As confidence builds, gradually move up to levels with more choices. Feel free to step down a level if things feel too complex.",
            'learninglevel2': "",
            'static_name': 'think_and_find',
        },
        'concept_quest': {
            'exercise_complexity': 1,
            'title': 'Concept Quest',
            'target': 'Size Concepts',
            'quote': '"Understanding size and spatial relationships is foundational for mathematical thinking and everyday reasoning" (Clements & Sarama, 2007).',
            'description': "Concept Quest is designed to help children learn and apply early size concepts such as long, short, tall, big, and small. By matching pictures or objects to these concepts, children develop their ability to compare, categorize, and describe the world around them. This exercise supports language development, visual discrimination, and conceptual reasoning, laying the groundwork for spatial understanding and mathematical skills.",
            'youtube_video_id': '5kcD24ov6-k',
            'bullet1': """Understand size descriptors - "Which one is long?""",
            'bullet2': """Identify spatial concepts - “Can you point to a tall tower?”""",
            'bullet3': """Apply comparative language: “Which one is smaller?”""",
            'learninglevel1': "Start with the easiest concepts and complexity level first e.g. big, small. As the child you're working with becomes more comfortable, you can gradually introduce more challenging concepts and try increasing complexity levels. Feel free to step down a level if things feel too complex.",
            'learninglevel2': "",
            'static_name': 'concept_quest',
        },
        'categorisation': {
            'exercise_complexity': 2,
            'title': 'Categorisation',
            'target': 'Sorting into Groups',
            'quote': '“Arranging thoughts, concepts and words into categories facilitate meaning, memory and retrieval” (Roth & Troia, 2005)',
            'description': "Categorisation levels up conceptual thinking by encouraging children to group things together based on similarities. Learning to group things together helps children understand and recall new words more easily, build their vocabulary, and clearly express ideas.",
            'youtube_video_id': 'Jbzs-x-ToZg',
            'bullet1': """Group items - "Which of these go together?""",
            'bullet2': """Identify categories - “What kind of thing is this?”""",
            'bullet3': """Compare and contrast: - “How are these similar?”""",
            'learninglevel1': "Start with the easiest level first. As the child you're working with gets better at grouping and identifying items, you can increase the difficulty step-by-step. Feel free to step down a level if things feel too complex.",
            'learninglevel2': "",
            'static_name': 'categorisation',
        },
        'story_train': {
            'exercise_complexity': 3,
            'title': 'Story Train',
            'target': 'Ordering Pictures',
            'quote': '',
            'description': "Story Train is a sequencing activity where children arrange pictures in specific orders to tell a story or show a process. This activity helps children to understand concepts such as time, order, and how events are connected. Sequencing also supports language development, comprehension, and logical thinking.",
            'youtube_video_id': 'uPJj3macND0',
            'bullet1': """Arrange events in order - "What happened first?""",
            'bullet2': """Describe actions and stories - “What is happening here?”""",
            'bullet3': """Use time words like "first", "next" and "then" """,
            'learninglevel1': "No need to select a learning level for this exercise, just click start and go for it!",
            'learninglevel2': "",
            'static_name': 'categorisation',
        },
        'story_train_advanced_sequencing': {
            'exercise_complexity': 3,
            'title': 'Story Train Plus',
            'target': 'Ordering Pictures',
            'quote': '',
            'description': 'Story Train Advanced introduces more complex narratives, a wider range of options, and less obvious sequences, encouraging deeper thinking about how events connect. This helps children develop a stronger understanding of time, cause and effect, and narrative structure. Sequencing at this level also supports more advanced language skills, including comprehension, reasoning, and the ability to organise and explain ideas clearly.',
            'youtube_video_id': '',
            'bullet1': 'Understand complex sequences by organising events in a logical and meaningful order',
            'bullet2': 'Develop reasoning skills by identifying cause, effect, and relationships between events',
            'bullet3': 'Improve narrative and language skills by explaining and describing sequences clearly',
            'learninglevel1': 'Begin with guided support, then encourage independent sequencing and explanation of choices as confidence grows.',
            'learninglevel2': '',
            'static_name': 'story_train',
        },
        'task_master_instructions': {
            'exercise_complexity': 3,
            'title': 'Task Master',
            'target': 'Instructions',
            'quote': '',
            'description': 'This activity helps children develop their ability to follow clear, structured instructions. By listening to and following specific instructions to place objects within a scene, children learn to organise information in the correct order and use precise, descriptive language. This activity supports understanding clarity in communication, and the understanding and use of instructional language. Research shows that practising step by step instructions helps children improve both their expressive language and their ability to convey information accurately.',
            'youtube_video_id': '',
            'bullet1': 'Listen to and  follow multi-step instructions',
            'bullet2': 'Use positional and descriptive vocabulary to place objects correctly within a scene',
            'bullet3': 'Develop expressive language skills by responding to and discussing instructions using clear, precise language',
            'learninglevel1': 'Start with familiar routines and scaffold the sequence, then fade support as confidence and precision increase.',
            'learninglevel2': '',
            'static_name': 'task_master',
        },
        'in_the_know_inferencing': {
            'exercise_complexity': 3,
            'title': 'In the Know',
            'target': 'Inferencing',
            'quote': '',
            'description': 'This activity helps children develop the ability to understand information that is not directly stated. By looking at clues in pictures, situations, or short scenarios, children learn to explain how they know something and justify their answers. This supports deeper comprehension, critical thinking, and the ability to connect ideas. Inferencing skills help children understand meaning beyond what is immediately conveyed.',
            'youtube_video_id': '',
            'bullet1': 'Use clues and prior knowledge to make informed inferences',
            'bullet2': 'Explain reasoning by answering "how do you know?" questions',
            'bullet3': 'Develop comprehension skills by understanding implied meaning',
            'learninglevel1': 'Start with explicit visual clues, then gradually increase ambiguity to build independent inferencing and explanation.',
            'learninglevel2': '',
            'static_name': 'in_the_know',
        },
        'what_happens_next_predicting': {
            'exercise_complexity': 3,
            'title': 'What Happens Next',
            'target': 'Predicting',
            'quote': '',
            'description': 'Predicting activities help children think ahead and anticipate what might happen next in a story or situation. By using visual clues, context, and prior knowledge, children learn to make logical predictions and explain their thinking. This supports comprehension, engagement, and the ability to understand how events are connected. Research shows that prediction strengthens understanding of narrative structure and helps children become more active, thoughtful learners.',
            'youtube_video_id': '',
            'bullet1': 'Make logical predictions based on clues and prior knowledge',
            'bullet2': 'Explain thinking when suggesting what might happen next',
            'bullet3': 'Understand sequences and the outcomes of different events',
            'learninglevel1': 'Start with clear visual sequences and scaffold predictions, then gradually reduce support as children justify their ideas independently.',
            'learninglevel2': '',
            'static_name': 'what_happens_next',
        },
        'spot_on': {
            'exercise_complexity': 1,
            'title': 'Spot On',
            'target': 'Prepositions',
            'description': "This activity helps children understand position words such as 'on, in, under, and next to'. By putting objects in the correct place, this activity teaches children how words can describe where things are. This hands-on approach makes it easier for children to understand spatial language, follow instructions, and describe the world around them. Research shows that learning through physical interaction and visual cues helps children understand and remember language concepts more clearly and effectively.",
            'youtube_video_id': '',
            'bullet1': "Understand position words such as 'on, in, under, and next to'.",
            'bullet2': 'Follow directional instructions - "put the teddy under the chair"',
            'bullet3': 'Develop spatial language to describe where objects are in relation to each other - "the dog is sitting next to the cat"',
            'learninglevel1': "Start with simple positions and fewer choices. As confidence builds, increase complexity and vary object placements.",
            'learninglevel2': '',
            'static_name': 'spot_on',
        },
        'whos_who_pronouns': {
            'exercise_complexity': 1,
            'title': "Who's Who?",
            'target': 'Pronouns',
            'description': "Pronoun activities help children understand 'who' words such as 'he, she, him, her, they and them'. In this activity, children learn how pronouns replace names and help us talk about people more easily. This interactive approach helps children connect words to people in a clear and meaningful way. This activity is a functional approach to learning, through giving children visual choices and simple actions, allowing them to remember and learn new words and ideas more easily.",
            'youtube_video_id': '',
            'bullet1': "Understand pronouns such as 'he, she, him, her, they and them'.",
            'bullet2': 'Identify the correct person when hearing a pronoun in a sentence or instruction - "give the ball to her".',
            'bullet3': 'Develop early grammar skills by linking pronouns to the people they correspond to - "he wants to play with the ball"',
            'learninglevel1': 'Start with clear visual contrasts and simple pronoun choices, then increase sentence complexity as confidence grows.',
            'learninglevel2': '',
            'static_name': 'whos_who',
        },
        'whats_in_the_bag_vocabulary_builder': {
            'exercise_complexity': 1,
            'title': "What's in the Bag?",
            'target': 'Vocabulary Builder',
            'description': 'This interactive activity helps children develop and expand their vocabulary. Children build their vocabulary by developing semantic links between names and objects. This activity encourages children to recognise, recall and say words independently. Research shows that repeated exposure to objects alongside active recall and visual cues, supports vocabulary development and helps children remember words more effectively.',
            'youtube_video_id': '',
            'bullet1': 'Build vocabulary by learning and naming everyday items',
            'bullet2': 'Develop the ability to recall information by identifying items when they appear',
            'bullet3': 'Strengthen semantic skills by connecting words to objects',
            'learninglevel1': 'Start with fewer familiar items, then increase the number and variety as confidence grows.',
            'learninglevel2': '',
            'static_name': 'whats_in_the_bag',
        }
    }