# Generated by Django 5.1.3 on 2026-01-27 18:22

import hashlib
from django.db import migrations


def hash_email(email):
    """Generate SHA256 hash of an email address."""
    if not email:
        return None
    return hashlib.sha256(email.lower().encode()).hexdigest()


def fix_encrypted_email_data(apps, schema_editor):
    """
    Fix malformed encrypted_email data that contains SQL expressions.
    
    This migration re-encrypts emails for users where the encrypted_email field
    contains a string representation of a SQL CASE/CAST expression instead of
    the actual encrypted value. This occurred due to bulk_update() bypassing
    Django's field encryption logic.
    """
    User = apps.get_model('accounts', 'User')
    
    fixed_count = 0
    skipped_count = 0
    
    for user in User.objects.all():
        # Check if email_encrypted contains SQL expression text
        if user.email_encrypted and isinstance(user.email_encrypted, str):
            if 'Cast(CASE' in user.email_encrypted or 'WHEN' in user.email_encrypted or 'WhereNode' in user.email_encrypted:
                # This is a malformed value - re-encrypt using the original email
                if user.email:
                    user.email_encrypted = user.email
                    user.email_hash = hash_email(user.email)
                    # Use save() with update_fields to trigger encryption
                    user.save(update_fields=['email_encrypted', 'email_hash'])
                    fixed_count += 1
                else:
                    # No email to fall back on - clear the malformed data
                    user.email_encrypted = None
                    user.email_hash = None
                    user.save(update_fields=['email_encrypted', 'email_hash'])
                    skipped_count += 1
    
    print(f"Fixed {fixed_count} users with malformed encrypted_email data")
    if skipped_count > 0:
        print(f"Cleared {skipped_count} users with malformed data but no email")


def reverse_fix(apps, schema_editor):
    """
    Reverse migration - no action needed as we've corrected the data.
    """
    print("Reverse migration: No action needed")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_randomize_usernames"),
    ]

    operations = [
        migrations.RunPython(
            fix_encrypted_email_data,
            reverse_fix,
        ),
    ]
