# Generated by Django 5.1.3 on 2026-01-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_randomize_usernames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
