# Generated by Django 5.1.3 on 2026-01-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_fix_encrypted_email_data"),
        ("accounts", "0005_remove_user_email_remove_user_first_name_and_more"),
    ]

    operations = []
