# Generated by Django 5.1.3 on 2026-07-22 13:01

from django.db import migrations
from django.utils import timezone


def grandfather_existing_users(apps, schema_editor):
    """Mark all existing users as email verified."""
    User = apps.get_model("accounts", "User")
    now = timezone.now()
    User.objects.all().update(email_verified=True, email_verified_at=now)


def reverse_grandfather(apps, schema_editor):
    """Reverse the grandfathering."""
    User = apps.get_model("accounts", "User")
    User.objects.all().update(email_verified=False, email_verified_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_email_verified_user_email_verified_at"),
    ]

    operations = [
        migrations.RunPython(grandfather_existing_users, reverse_grandfather),
    ]
