# Generated by Django 4.2.16 on 2024-12-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
