# Generated by Django 4.2.16 on 2024-12-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0003_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='age',
        ),
        migrations.AddField(
            model_name='learner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
