# Generated by Django 4.2.16 on 2024-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0004_remove_learner_age_learner_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
