# Generated by Django 4.2.16 on 2024-12-28 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0005_alter_learner_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='learner_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
