# Generated by Django 4.2.16 on 2024-12-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0006_learner_learner_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
