# Generated by Django 3.2.25 on 2024-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0007_learner_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
