# Generated by Django 3.2.25 on 2025-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0008_learner_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='learner',
            name='assessment1',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='assessment2',
            field=models.CharField(blank=True, choices=[('poor', 'Poor'), ('average', 'Average'), ('excellent', 'Excellent')], max_length=50, null=True),
        ),
    ]
