# Generated by Django 4.2.16 on 2025-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0009_auto_20250103_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='assessment1',
            field=models.IntegerField(blank=True, choices=[(1, 'Limited vocabulary with some understanding and use of subject and verb eg. the dog is running'), (2, 'Can determine differences between objects and find objects based on verbal or visual information eg. find the big, red hat'), (3, 'Can sort items into categories and find similarities eg. which of these are animals?'), (4, 'Can retell a story or describe an event step by step eg. how do you brush your teeth?'), (5, 'Can make their own predictions about an event eg. the girl is standing by the river, what might she do next?'), (6, 'Is able to do all of the above and is looking to practise or build on their current skills')], null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='assessment2',
            field=models.IntegerField(blank=True, choices=[(1, 'Knows some common verbs eg. running, jumping, sleeping, eating'), (2, 'Uses verbs in a sentence e.g. The dog is playing'), (3, 'Uses objects in a sentence eg. The dog was playing with a ball'), (4, 'Often uses location in a sentence e.g. I was playing in the playground'), (5, 'Often uses adjectives in a sentence eg. my jumper is fluffy'), (6, 'Often uses when in a sentence eg. In the morning, I’m going to the park')], null=True),
        ),
    ]
