# Generated by Django 3.2.25 on 2025-01-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0010_alter_learner_assessment1_alter_learner_assessment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
