# Generated by Django 3.2.25 on 2025-03-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0014_auto_20250310_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='learner',
            field=models.ForeignKey(blank=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='littleTalkApp.learner'),
        ),
    ]
