# Generated by Django 3.2.25 on 2025-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0015_logentry_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
