# Generated by Django 3.2.25 on 2025-03-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0016_alter_logentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
