# Generated by Django 4.2.16 on 2025-04-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0017_logentry_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='littleTalkApp.learner'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
