# Generated by Django 3.2.25 on 2025-05-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0019_assessment_assessmentanswer_assessmentquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hear_about',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LearnerAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('answer', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='littleTalkApp.learner')),
            ],
        ),
    ]
