# Generated by Django 3.2.25 on 2025-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0020_auto_20250507_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opted_in',
            field=models.BooleanField(default=False),
        ),
    ]
