# Generated by Django 4.2.16 on 2025-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0021_profile_opted_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
