# Generated by Django 4.2.16 on 2025-05-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0022_alter_learner_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentanswer',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentAnswer',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
    ]
