# Generated by Django 4.2.16 on 2025-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0023_remove_assessmentanswer_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='recommendation_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
