# Generated by Django 5.1.3 on 2025-06-17 17:51

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0024_learner_recommendation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
