# Generated by Django 5.1.3 on 2025-07-24 15:20

import django.db.models.deletion
import littleTalkApp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0028_remove_cohort_user_remove_learner_user_profile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('staff', 'Staff')], default='staff', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=littleTalkApp.models.default_expiry)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='littleTalkApp.school')),
            ],
        ),
    ]
