# Generated by Django 5.1.3 on 2025-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0030_staffinvite_sent_by_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('team_manager', 'Team Manager'), ('staff', 'Staff'), ('read_only', 'Read Only')], max_length=30),
        ),
    ]
