# Generated by Django 5.1.3 on 2025-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0031_alter_staffinvite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinvite',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
