# Generated by Django 5.1.3 on 2025-07-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0033_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='message',
        ),
    ]
