# Generated by Django 5.1.3 on 2025-07-30 10:35

import littleTalkApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0035_parentaccesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentaccesstoken',
            name='used',
        ),
        migrations.AlterField(
            model_name='parentaccesstoken',
            name='expires_at',
            field=models.DateTimeField(default=littleTalkApp.models.default_expiry),
        ),
    ]
