# Generated by Django 5.1.3 on 2025-07-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0036_remove_parentaccesstoken_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentaccesstoken',
            name='learner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_token', to='littleTalkApp.learner'),
        ),
    ]
