# Generated by Django 5.1.3 on 2025-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0037_alter_parentaccesstoken_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccesstoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentaccesstoken',
            name='token',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
