# Generated by Django 5.1.3 on 2025-07-30 14:18

import django.db.models.deletion
import littleTalkApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0038_parentaccesstoken_used_alter_parentaccesstoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(default=littleTalkApp.models.default_trial_end)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('learners', models.ManyToManyField(related_name='parents', to='littleTalkApp.learner')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='littleTalkApp.profile')),
            ],
        ),
    ]
