# Generated by Django 5.1.3 on 2025-08-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0039_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='is_standalone',
            field=models.BooleanField(default=False),
        ),
    ]
