# Generated by Django 5.1.3 on 2025-08-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0041_learner_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='created_by',
        ),
    ]
