# Generated by Django 5.1.3 on 2025-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0042_remove_learner_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
