# Generated by Django 5.1.3 on 2025-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0043_logentry_created_by_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='license_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
