# Generated by Django 5.1.3 on 2025-08-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0044_school_is_licensed_school_license_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
