# Generated by Django 5.1.3 on 2025-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0046_learner_user_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('team_manager', 'Team Manager'), ('staff', 'Staff'), ('read_only', 'Read Only')], default='parent', max_length=20),
        ),
    ]
