# Generated by Django 5.1.3 on 2025-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0051_migrate_all_to_parent_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='total_exercises',
            field=models.IntegerField(default=0),
        ),
    ]
