# Generated by Django 5.1.3 on 2025-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0052_learner_total_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='littleTalkApp.school'),
        ),
    ]
