# Generated by Django 5.1.3 on 2025-10-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0053_profile_schools"),
    ]

    def copy_profile_school_to_m2m(apps, schema_editor):
        Profile = apps.get_model("littleTalkApp", "Profile")
        School = apps.get_model("littleTalkApp", "School")
        for profile in Profile.objects.all():
            if profile.school_id:
                try:
                    profile.schools.add(profile.school_id)
                except Exception:
                    # guard against bad data, or log
                    pass

    def reverse_func(apps, schema_editor):
        # Remove the mappings we added in the forward migration.
        # This is safe as a rollback: it will remove the link from the
        # M2M table for profiles whose `school` FK matched an entry.
        Profile = apps.get_model("littleTalkApp", "Profile")
        for profile in Profile.objects.all():
            if profile.school_id:
                try:
                    profile.schools.remove(profile.school_id)
                except Exception:
                    # ignore any problems during rollback
                    pass

    operations = [
        migrations.RunPython(copy_profile_school_to_m2m, reverse_func),
    ]
