# Generated by custom edit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0054_copy_profile_school_to_many"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolMembership",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="memberships",
                        to="littleTalkApp.Profile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="memberships",
                        to="littleTalkApp.School",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("team_manager", "Team Manager"),
                            ("staff", "Staff"),
                            ("read_only", "Read Only"),
                            ("parent", "Parent"),
                        ],
                        default="staff",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("profile", "school")},
                "indexes": [models.Index(fields=["school", "role"], name="ltapp_sch_role_idx"), models.Index(fields=["profile"], name="ltapp_profile_idx")],
            },
        ),
    ]
