# Generated by Django 5.1.3 on 2025-11-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0055_schoolmembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schoolmembership',
            new_name='littleTalkA_school__ad30fa_idx',
            old_name='ltapp_sch_role_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolmembership',
            new_name='littleTalkA_profile_f29eea_idx',
            old_name='ltapp_profile_idx',
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
