# Generated by Django 5.1.3 on 2025-11-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleTalkApp', '0056_populate_schoolmembership'),
        ('littleTalkApp', '0056_rename_ltapp_sch_role_idx_littletalka_school__ad30fa_idx_and_more'),
    ]

    operations = [
    ]
