# Generated by Django 5.1.3 on 2025-12-31 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0060_remove_profile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_id", models.CharField(max_length=255)),
                ("difficulty_selected", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("total_questions", models.IntegerField()),
                ("incorrect_answers", models.IntegerField()),
                ("attempts_per_question", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_sessions",
                        to="littleTalkApp.learner",
                    ),
                ),
            ],
        ),
    ]
