# Generated by Django 5.1.3 on 2026-01-14 21:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0061_exercisesession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="exercises_practised",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="goals",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="notes",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
