# Generated by Django 5.1.3 on 2026-01-16 14:40

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0063_encrypt_learner_dob_age_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
