# Generated by Django 5.1.3 on 2026-01-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0065_encrypt_sensitive_fields_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WaitingList",
        ),
    ]
