# Generated by Django 5.1.3 on 2026-01-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0066_delete_waitinglist"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['learner', 'created_at'], name='exsess_lrnr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['learner', 'exercise_id', 'created_at'], name='exsess_lrnr_exercise_idx'),
        ),
    ]
