# Generated by Django 5.1.3 on 2026-02-02 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0067_add_exercisesession_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerassessmentanswer",
            name="assessment_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="learnerassessmentanswer",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
