# Generated by Django 5.1.3 on 2026-02-03 16:18

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0068_learnerassessmentanswer_assessment_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("---", "Not Set"),
                            ("achieved", "Achieved"),
                            ("not_achieved", "Not Achieved"),
                            ("ongoing", "Ongoing"),
                        ],
                        default="---",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="littleTalkApp.learner",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
