# Generated by Django 5.1.3 on 2026-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0070_skolon_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisesession",
            name="learner_total_exp_after_session",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
