# Generated by Django 5.1.3 on 2026-06-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0076_normalize_legacy_exercisesession_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="learner",
            name="avatar_character",
            field=models.CharField(default="blank_profile_picture", max_length=64),
        ),
        migrations.AddField(
            model_name="learner",
            name="avatar_color",
            field=models.CharField(default="#DEE2E6", max_length=7),
        ),
    ]
