# Generated by Django 5.1.3 on 2026-06-08 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0077_learner_avatar_character_learner_avatar_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolLicenseCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_by_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_license_codes",
                        to="littleTalkApp.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="littleTalkA_code_adc39f_idx"
                    )
                ],
            },
        ),
    ]
