# Generated by Django 5.1.3 on 2026-07-22 13:01

import django.db.models.deletion
import littleTalkApp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0078_schoollicensecode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        help_text="6-character verification code",
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "link_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID for the click-link verification URL",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of failed verification attempts"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=littleTalkApp.models.default_expiry,
                        help_text="When this code expires",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "used"], name="littleTalkA_user_id_15581f_idx"
                    )
                ],
            },
        ),
    ]
