# Generated by Django 5.1.3 on 2026-07-31 09:34

import django.db.models.deletion
import littleTalkApp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0087_staffinvite_finalize_encrypted_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID for the password reset link",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=littleTalkApp.models.default_expiry,
                        help_text="When this reset link expires",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "used"], name="littleTalkA_user_id_256f48_idx"
                    )
                ],
            },
        ),
    ]
