# Generated by Django 5.1.3 on 2026-08-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littleTalkApp", "0088_passwordresettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="intervention_groups",
                        to="littleTalkApp.learner",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_groups",
                        to="littleTalkApp.school",
                    ),
                ),
            ],
        ),
    ]
