QUESTIONS = [
    {"topic": "Receptive Language", "text": "Can your child attend to an activity for 5 minutes?", "order": 1},
    {"topic": "Receptive Language", "text": "Does your child seem to understand what you're saying most of the time?", "order": 2},
    {"topic": "Receptive Language", "text": "Can your child respond to simple 'yes/no' or 'what' questions through speech or gesture?", "order": 3},
    {"topic": "Receptive Language", "text": "Can your child answer 'where' or 'who' questions?", "order": 4},
    {"topic": "Receptive Language", "text": "Can your child follow simple directions like 'get your shoes' or 'sit down'?", "order": 5},
    {"topic": "Receptive Language", "text": "Can your child follow multi-step directions like 'put your shoes on and wait by the door'?", "order": 6},
    {"topic": "Receptive Language", "text": "Does your child understand concepts like 'big and small'?", "order": 7},
    {"topic": "Receptive Language", "text": "Can your child group items that belong together? eg. animals, foods, items of clothing", "order": 8},
    {"topic": "Receptive Language", "text": "Can your child answer 'why' or 'how' questions?", "order": 9},
    {"topic": "Expressive Language", "text": "Does your child typically use sentences with two or more words?", "order": 10},
    {"topic": "Expressive Language", "text": "Does your child use new words regularly?", "order": 11},
    {"topic": "Expressive Language", "text": "Do they repeat the same words or phrases often?", "order": 12},
    {"topic": "Expressive Language", "text": "Can your child name everyday items? eg. car, cup, hat, chair etc.", "order": 13},
    {"topic": "Expressive Language", "text": "Does your child mix up word order in sentences?", "order": 14},
    {"topic": "Expressive Language", "text": "Does your child use complete sentences?", "order": 15},
    {"topic": "Expressive Language", "text": "Does your child ever struggle to find the right word?", "order": 16},
    {"topic": "Expressive Language", "text": "Do they get frustrated when they can't think of what to say?", "order": 17},
    {"topic": "Expressive Language", "text": "Can your child retell something that happened at school or in a story?", "order": 18},
    {"topic": "Expressive Language", "text": "Does your child describe events in a logical order, or do they often shift topics or skip around?", "order": 19}
]