GAME_DESCRIPTIONS = {
        'colourful_semantics': {
            'exercise_complexity': 0,
            'title': 'Colourful Semantics',
            'target': 'Sentence Building',
            'description': "Colourful Semantics helps children understand what words mean, how words fit together, and how to create simple, meaningful sentences. It uses colors to group words, making it easier for your child to remember words, learn new vocabulary, and express themselves clearly. Research shows that visual grouping of words into colors helps children better understand language and remember words more effectively.",
            'bullet1': """Name objects, people, actions - “What is this?”""",
            'bullet2': """Repeat a sentence - "Let's say, the dog is sitting.”""",
            'bullet3': """Describe a scene - “What's happening in this picture?”""",
            'learninglevel1': "If the child you are practising with is still learning their first few words (around 5 words or less), try the first two easier levels. These will focus on learning nouns (names of things and people) and verbs (action words). Many children find verbs tricky at first, so these levels will help.",
            'learninglevel2': 'If they already know some words and you want to help them start building sentences, pick higher difficulty levels to encourage them to put words together into simple sentences.',
            'static_name': 'colourful_semantics',
        },
        'think_and_find': {
            'exercise_complexity': 1,
            'title': 'Think and Find',
            'target': 'Identifying General Concepts',
            'quote': '"Linking items to concepts helps children structure their thoughts and enhances memory and retrieval capabilities" (Anderson & Freebody, 1981).',
            'description': "Think and Find is a fun matching activity that helps children learn new words and practice important thinking skills. It encourages children to develop conceptual thinking by matching pictures based on characteristics, improving their ability to notice details and make connections. This supports language growth, memory, and decision-making. It also serves as a natural path to categoristaion.",
            'bullet1': """Point to / find an object - “Can you point to the lorry?”""",
            'bullet2': """Match pictures and objects - “Can you find a car like this?”""",
            'bullet3': """Identify & describe characteristics: “What shape is this?”""",
            'learninglevel1': "We recommend starting with the easiest level first. As confidence builds, gradually move up to levels with more choices. Feel free to step down a level if things feel too complex.",
            'learninglevel2': "",
            'static_name': 'think_and_find',
        },
        'concept_quest': {
            'exercise_complexity': 1,
            'title': 'Concept Quest',
            'target': 'Identifying Concepts',
            'quote': '"Understanding size and spatial relationships is foundational for mathematical thinking and everyday reasoning" (Clements & Sarama, 2007).',
            'description': "Concept Quest is an engaging activity designed to help children learn and apply early size concepts such as long, short, tall, big, and small. By matching pictures or objects to these concepts, children develop their ability to compare, categorize, and describe the world around them. This exercise supports language development, visual discrimination, and conceptual reasoning, laying the groundwork for spatial understanding and mathematical skills.",
            'bullet1': """Understand size descriptors - “Which one is long?”""",
            'bullet2': """Identify spatial concepts - “Can you point to a tall tower?”""",
            'bullet3': """Apply comparative language: “Which one is smaller?”""",
            'learninglevel1': "Start with the easiest concepts and complexity level first e.g. big, small. As the child you're working with becomes more comfortable, you can gradually introduce more challenging concepts and try increasing complexity levels. Feel free to step down a level if things feel too complex.",
            'learninglevel2': "",
            'static_name': 'concept_quest',
        },
        'categorisation': {
            'exercise_complexity': 2,
            'title': 'Categorisation',
            'target': 'Sorting into Groups',
            'quote': '“Arranging thoughts, concepts and words into categories facilitate meaning, memory and retrieval” (Roth & Troia, 2005)',
            'description': "Categorisation is an activity that levels up conceptual thinking by encouraging children group things together based on similarities. Learning to group things together helps children understand and recall new words more easily, build their vocabulary, and clearly express ideas.",
            'bullet1': """Group items - “Which of these go together?”""",
            'bullet2': """Identify categories - “What kind of thing is this?”""",
            'bullet3': """Compare and contrast: - “How are these similar?”""",
            'learninglevel1': "Start with the easiest level first. As the child you're working with gets better at grouping and identifying items, you can increase the difficulty step-by-step. Feel free to step down a level if things feel too complex.",
            'learninglevel2': "",
            'static_name': 'categorisation',
        },
        'story_train': {
            'exercise_complexity': 3,
            'title': 'Story Train',
            'target': 'Ordering Pictures',
            'quote': '',
            'description': "Story Train is a fun sequencing activity where children arrange pictures in specific orders to tell a story or show a process. This activity helps children to understand concepts such as time, order, and how events are connected. Sequencing also supports language development, comprehension, and logical thinking.",
            'bullet1': """Arrange events in order - “What happened first?”""",
            'bullet2': """Describe actions and stories - “What is happening here?”""",
            'bullet3': """Use time words like "first", "next" and "then" """,
            'learninglevel1': "No need to select a learning level for this exercise, just click start and go for it!",
            'learninglevel2': "",
            'static_name': 'categorisation',
        }
    }